export default {
  name: "维默观影",
  menus: [
    { name: "movie", path: "/movie", label: "电影", component: "MovieView" },
    { name: "tv", path: "/tv", label: "电视剧", component: "TvView" },
    { name: "ustv", path: "/ustv", label: "美剧", component: "UsView" },
    { name: "krtv", path: "/krtv", label: "韩剧", component: "KrView" },
    {
      name: "variety",
      path: "/variety",
      label: "综艺",
      component: "VarietyView",
    },
    { name: "anime", path: "/anime", label: "动漫", component: "AnimeView" },
    { name: "food", path: "/food", label: "下饭", component: "FoodView" },
    { name: "live", path: "/live", label: "直播", component: "LiveView" },
    {
      name: "favorites",
      path: "/favorites",
      label: "爱看",
      component: "FavoritesView",
    },
    { name: "reward", path: "/reward", label: "赞赏", component: "RewardView" },
    {
      name: "contact",
      path: "/contact",
      label: "联系我",
      component: "ContactView",
    },
  ],
  dataSources: {
    movie: "/data/movies.json",
    tv: "/data/tv.json",
    ustv: "/data/ustv.json",
    krtv: "/data/krtv.json",
    variety: "/data/variety.json",
    anime: "/data/anime.json",
    food: "/data/food.json",
    live: "/data/live.json",
    password: "/data/password.json",
  },
};
